### ISSUE TITLE
Quota limit exceeded causes crash

### ISSUE THREAD

**Issue by scottcorgan** [kenperkins/winston-papertrail#37]
Getting an upstream cannot connect error when we've exceeded our Papertrail quota. Did this type of error get caught in any release after `0.1.5`?

**Comment by kenperkins** [comment]
I can't recall off the top of my head specific changes that would cause this, but I don't think that it should refuse connection; maybe @troy might know...

**Comment by troy** [comment]
Papertrail does refuse connections if the account limit is reached. This shouldn't be considered a fatal error, though, since many other causes (network unreachability, firewall policy, etc) can cause a port unreachable, host unreachable, or connection timeout. It's a noteworthy error but not one that should affect the app. Let me know if I can clarify typical behavior or otherwise help.

**Comment by scottcorgan** [comment]
We had an incident recently where our Papertrail account went over limit. It caused all sorts of crashes on the server. I know I can write my own connection error handling, but I was more curious why things crashed when this module was unable to connect upstream.

**Comment by kenperkins** [comment]
@scottcorgan I'll get a fix asap. Sorry about that; you're correct that the transport shouldn't crash your server.

**Comment by kenperkins** [comment]
@scottcorgan what version of `winston-papertrail` are you using?

**Comment by scottcorgan** [comment]
The latest

**Comment by kenperkins** [comment]
I'm unable to reproduce this error, even with an invalid port that creates an `ECONNREFUSED` error. Can you tell me what error you're getting? @troy is there a way to replicate the behavior? Should `ECONNREFUSED` be good enough?

**Comment by troy** [comment]
Yes, it would either be that or a similar ICMP error message like port unreachable.

**Comment by scottcorgan** [comment]
I was unable to reproduce with bad port and host as well. It only happens when the account is over the limit. The error got lost in the Elastic Beanstalk logs. It was something like "cannot connect upstream".

If it's something out of the scope of this module, I'll close issue.

**Comment by troy** [comment]
@scottcorgan was the attempted repro you mentioned above (which failed) also on Elastic Beanstalk? I'm wondering if it's something specific to EB rather than to the difference between an inactive port and an active one over limit (which, as far as I know, are completely indistinguishable from one another -- we don't listen on the port).

**Comment by scottcorgan** [comment]
Yes, it was on EB, which may have well produced that connection error. It's kind of a black box in there. Either way, I'll close the issue and post if anything comes up again.
